markdown_extensions:
  - md_in_html
extra_css:
  - css/extra.css
site_name: Intelligent Textbook for Applied Linear Algebra
repo_url: https://github.com/ArtemisPearson/learning-graphs
nav:
  - Home: index.md
  - List of Chapters:
    - Overview: sections/index.md
    - Section 1: 
      - Overview: sections/section-1/section-1.md
      - Chapter 1: sections/section-1/chapter-1/chapter-1.md
      - Chapter 2: sections/section-1/chapter-2/chapter-2.md
      - Chapter 3: sections/section-1/chapter-3/chapter-3.md
      - Chapter 4: sections/section-1/chapter-4/chapter-4.md
      - Chapter 5: sections/section-1/chapter-5/chapter-5.md
      - Chapter 6: sections/section-1/chapter-6/chapter-6.md
    - Section 2: 
      - Overview: sections/section-2/section-2.md
      - Chapter 7: sections/section-2/chapter-7/chapter-7.md
      - Chapter 8: sections/section-2/chapter-8/chapter-8.md
      - Chapter 9: sections/section-2/chapter-9/chapter-9.md
      - Chapter 10: sections/section-2/chapter-10/chapter-10.md
    - Section 3: 
      - Overview: sections/section-3/section-3.md
      - Chapter 11: sections/section-3/chapter-11/chapter-11.md
      - Chapter 12: sections/section-3/chapter-12/chapter-12.md
      - Chapter 13: sections/section-3/chapter-13/chapter-13.md
    - Section 4: 
      - Overview: sections/section-4/section-4.md
      - Chapter 14: sections/section-4/chapter-14/chapter-14.md
      - Chapter 15: sections/section-4/chapter-15/chapter-15.md
      - Chapter 16: sections/section-4/chapter-16/chapter-16.md
    - Section 5: 
      - Overview: sections/section-5/section-5.md
      - Chapter 17: sections/section-5/chapter-17/chapter-17.md
      - Chapter 18: sections/section-5/chapter-18/chapter-18.md
      - Chapter 19: sections/section-5/chapter-19/chapter-19.md
      - Chapter 20: sections/section-5/chapter-20/chapter-20.md
      - Chapter 21: sections/section-5/chapter-21/chapter-21.md

theme:
  name: material
